### ISSUE TITLE
Fortran MPI+OpenMP mpi2dim: Error! unregistered event type

### ISSUE THREAD

**Issue by hpcbern** [bsc-performance-tools/extrae#100]
Hello,

after executing a hybrid (MPI+OpenMP) Fortran program (using extrae 4.0.3, gcc 10.2.0, mpt 2.26)
after LD_PRELOADing libompitracef.so within a wrapper script
(and trace enabled="yes" type="dimemas", mpi enabled="yes", openmp enabled="yes" ompt="no", merge enabled="no"
in the config xml) there were first only just some warnings like
`Extrae: WARNING! omp_get_thread_num_real is a NULL pointer. Did the initialization of this module trigger? Retrying initialization...`

But trying to run mpi2dim afterwards, there were many errors like
`mpi2dim: Error! unregistered event type 40000133 in Dimemas_ProcessTraceFiles+459`
with types 40000002,40000033, 40000133, 60000001, 60000018, 60000060...

This happened for a production code as well as a small test code and
a workaround was to use type="paraver" and the prv2dim conversion tool.

But where do these errors come from and how can they be avoided?
Is there anything special to take care of?

Thank you,
 Martin

**Comment by gllort** [comment]
Hi Martin,

The two issues you mentioned are unrelated:

1) The warning `omp_get_thread_num_real is a NULL pointer. Did the initialization of this module trigger? Retrying initialization..."`, is related to the initialization of the tracing and the OpenMP libraries. There's some points during Extrae's initialization where the OpenMP libraries are not loaded yet, so we can't resolve the function pointers to their methods. This has a fallback mechanism and these symbols are resolved later, so this shouldn't be a problem. If there are OpenMP events in the trace, you can safely disregard this warning. 

2) `mpi2dim` is currently deprecated. The `unregistered event type` errors refer to events that were added more recently that the tool does not expect. The recommended way to proceed would be what you are already doing: using type="paraver" and the prv2dim conversion tool. 

Hope this helps!
-- G.

**Comment by hpcbern** [comment]
Hi Germán,

I already speculated that the extrae warning is not important, but wanted
to include every type of errors and warnings here.
(Is it possible to choose a verbose levels to turn off unimportant warnings?).

I missed the fact that mpi2dim is deprecated (have to read the docs).
Is type="paraver" now the only useful extrae setting in the xml
trace-section for this case?
It would have been helpful for me if (also) a "mpi2dim deprecation" warning
(and maybe a hint to use type="paraver" + prv2dim) would be printed,
if type="dimemas" is set.

Thank you,
 Martin

**Comment by gllort** [comment]
Sorry for the late reply. We'll try to improve deprecation warnings in the documentation!

1. No, there's no option to choose the verbosity level, but it's an interesting idea. We'll take note of it, thanks!
2. Yes, type="paraver" is basically the only useful setting nowadays. It is still possible to use type="dimemas", but you'd need to rollback Dimemas to a quite old version, which I wouldn't recommend.

Best regards,
-- G.
