### ISSUE TITLE
Internal Error: insert(): Duplicate key found! - using Extrae_event

### ISSUE THREAD

**Issue by stefandesouza** [bsc-performance-tools/extrae#109]
Hello. I'm currently trying to add timestamped events into my trace file using the Extrae API. The application is an OpenFOAM11 solver that uses foamRun. This is the error I get
`Internal Error: insert(): Duplicate key found!`
repeated for as many MPI processors I have running. This is what my instrumentation looks like

```
  #include "extrae.h"
  #include "extrae_user_events.h"
  ...
  extrae_type_t type = 1000;
  unsigned int nvalues = 4;
  extrae_value_t values[4] = {0, 1, 2, 3};
  char * description_values[4] = {"End", "Begin", "After Presolve", "Before Postsolve"};

  Extrae_define_event_type (&type, "Kernel execution", &nvalues, values, description_values);

  while (pimple.run(runTime))
  {
      Extrae_event (1000,1);
      solver.preSolve();
      Extrae_event (1000,2);
      // Adjust the time-step according to the solver maxDeltaT
      adjustDeltaT(runTime, solver);

      runTime++;

      while (pimple.loop())
      {
          solver.moveMesh();
          solver.fvModels().correct();
          solver.prePredictor();
          solver.momentumPredictor();
          solver.thermophysicalPredictor();
          solver.pressureCorrector();
          solver.postCorrector();
      }
      Extrae_event (1000,3);
      solver.postSolve();
      Extrae_event (1000,0);

      runTime.write();
  }

  Info<< "End\n" << endl;

  return 0;
```
And my linking commands
```
EXE_INC = \
    -I$(LIB_SRC)/finiteVolume/lnInclude -I$(EXTRAE_HOME)/include

EXE_LIBS = \
    -lfiniteVolume -Wl,-rpath -Wl,$(EXTRAE_HOME)/lib -L$(EXTRAE_HOME)/lib -lmpitrace
```

Edit: Seems to run fine while omitting the `LD_PRELOAD` in my job script.

**Comment by gllort** [comment]
We don't identify this error as being produced by Extrae. There are no calls to any method named 'insert' in our code, and no operations related to inserting keys in a dictionary in relation to manual instrumentation. I'm more inclined to think that adding the tracing library modifies the memory disposition (or corrupts memory somehow) and this affects an operation of the application itself.

Can you first try upgrading to the latest version (4.2.1), and also remove the call to Extrae_define_event_type? This will result in adding events into the trace without labels, which will show as Unknown in Paraver. However, this is to verify whether this API call introduces the problem or not.

**Comment by stefandesouza** [comment]
Hi,
The issue seemed to be that I was both linking the trace library during compilation as well as pre-loading it in my job script. Taking out the `LD_PRELOAD` export seemed to solve the problem. Thank you for the help.
