### ISSUE TITLE
FR: Add support for MPI RMA atomics and passive mode

### ISSUE THREAD

**Issue by devreal** [bsc-performance-tools/extrae#2]
Dear Extrae Devs,

I am using Extrae and Paraver to analyze the behavior of my application that's entirely based on MPI-3 RMA. I noticed that Extrae does not cover all MPI functions that are relevant for my code, most notable some of the atomic operations (`MPI_Fetch_and_op` and `MPI_Compare_and_swap`) as well as passive window synchronization (`MPI_Win_flush*`). I've been trying to add support myself following the example of `MPI_Get_accumulate` but seem to run into some memory corruption. Before going down this road further I wanted to ask whether there is already support for these functions available as a patch or in a branch, just to avoid duplicating work. Please let me know if there is, I'm also happy to test development patches.

**Comment by emercadal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FR: Add support for MPI RMA atomics and passive mode](https://trello.com/c/fQ8STW4G/62-fr-add-support-for-mpi-rma-atomics-and-passive-mode)
