### ISSUE TITLE
1a215e849 breaks instrumentation for applications with signals

### ISSUE THREAD

**Issue by lucjaulmes** [bsc-performance-tools/extrae#24]
`dladdr` is not reentrant, in fact it calls a mutex. So if an application has signals (say `SIGALRM` to execute some code periodically), the signal may happen while Extrae's `LookForUFaddress` is inside `dladdr`, and it will call it again to instrument the function in the signal handler.

This causes the application to hang forever with a backtrace looking like this (where `trigger` is the signal handler):
```
#0  0x00007ffff7402c94 in __lll_lock_wait () from /usr/lib64/libpthread.so.0
#1  0x00007ffff73fb6a0 in pthread_mutex_lock () from /usr/lib64/libpthread.so.0
#2  0x00007ffff7981a38 in _dl_addr () from /lib64/libc.so.6
#3  0x00007ffff74a1d50 in dladdr () from /usr/lib64/libdl.so.2
#4  0x00007ffff7c18744 in LookForUFaddress (address=<optimized out>) at ../../../src/tracer/UF_gcc_instrument.c:157
#5  0x00007ffff7c1885c in __cyg_profile_func_enter (this_fn=0x7ffff7b78e90 <trigger>, call_site=<optimized out>)
    at ../../../src/tracer/UF_gcc_instrument.c:84
#6  0x00007ffff7b78edc in trigger (signo=<optimized out>, siginfo=0x7fffffffaa58, ctx=<optimized out>) at vulnerability.c:418
#7  <signal handler called>
#8  0x00007ffff73fb680 in pthread_mutex_lock () from /usr/lib64/libpthread.so.0
#9  0x00007ffff7981a38 in _dl_addr () from /lib64/libc.so.6
#10 0x00007ffff74a1d50 in dladdr () from /usr/lib64/libdl.so.2
#11 0x00007ffff7c18744 in LookForUFaddress (address=<optimized out>) at ../../../src/tracer/UF_gcc_instrument.c:157
#12 0x00007ffff7c189f4 in __cyg_profile_func_exit (this_fn=<optimized out>, call_site=<optimized out>) at ../../../src/tracer/UF_gcc_instrument.c:110
[...]
```

This has happened to me with a preloaded extrae and user functions enabled, using gcc's `-finstrument-functions`.

A solution could be to user the addresses of the symbols directly rather than their relative address in the library, or to mask signals for the call and restore them afterwards, or even to use a reentrant alternative to dladdr.

**Comment by emercadal** [comment]
c56d85e2efe1e8b90d6a51a7d89d69b35b108d11 removes `dladdr` to translate adresses.
