### ISSUE TITLE
Extrae build fails with binutils-2.34

### ISSUE THREAD

**Issue by TovRudyy** [bsc-performance-tools/extrae#44]
binutils-2.34 changes some functions signatures causing _undefined reference_ error when linking Extrae. The binutils porting problem has been reported [here](https://wiki.gentoo.org/wiki/Binutils_2.34_porting_notes/undefined_reference_to_bfd_get_section_*)

The problem is easily circumvented by replacing the undefined references with the actual names:
```
vma = bfd_get_section_vma (abfd, section);; -> vma = bfd_section_vma (section);; 
size = bfd_get_section_size (section); -> size = bfd_section_size (section);
if ((bfd_get_section_flags (abfd, section) & SEC_ALLOC) == 0) -> if ((bfd_section_flags (section) & SEC_ALLOC) == 0)
```

**Comment by emercadal** [comment]
#42 #43
