### ISSUE TITLE
CUDA build fails

### ISSUE THREAD

**Issue by loveshack** [bsc-performance-tools/extrae#47]
Building --with-cuda fails because Extrae_cudaLaunch_Enter is called with only one argument at line 144 in src/tracer/wrappers/CUDA/cuda_wrapper.c.  Should the second argument there be NULL?

**Comment by emercadal** [comment]
Thanks for the report. Yes in this case the second argument should be NULL.

For a more up-to-date CUDA instrumentation we suggest using the CUPTI interface by adding the option --with-cuda-cupti=CUDA_HOME/extras/CUPTI to Extrae's configure line.

**Comment by loveshack** [comment]
> For a more up-to-date CUDA instrumentation we suggest using the CUPTI
> interface by adding the option
> --with-cuda-cupti=CUDA_HOME/extras/CUPTI to Extrae's configure line.

Thanks.  Yes, I was specifying cupti, but configure wants --with-cuda
and --with-cupti; I don't see a combined option in the current release.

**Comment by emercadal** [comment]
No, we don't provide a combined option, to use CUPTI you need to specify both `--with-cuda` and `--with-cupti`.

**Comment by emercadal** [comment]
Closed by https://github.com/bsc-performance-tools/extrae/commit/0a84e0a0eac2befaa43039977ed03bd9d4a1c9e7
