### ISSUE TITLE
Extrae build failure on IBM power 8

### ISSUE THREAD

**Issue by sheltongeosx** [bsc-performance-tools/extrae#48]
Dear BSC Developers

I am trying to build extrae on IBM power 8 machine but it failed compiling commonSnippets.C. The following are the build environments and error messages.

    Build environment:
        Machine: IBM Power 8
        OS: Red Hat Enterprise Linux Server 7.4 (Maipo)
        Compiler: GCC/8.2.0
        CUDA: cuda/10.1
        OpenMPI: 4.0.1
        Boost:  1.72.0
        dyninst: 10.1.0
        extrae commit: 5ccdf0c, 2020-08-21 19:43:13, tag 3.8.3

    Error messages:
        commonSnippets.C: In function std::__cxx11::string decodeBasicBlocks(BPatch_function*, std::__cxx11::string):
        commonSnippets.C:486:34: error: no match for operator= (operand types are Dyninst::InstructionAPI::Instruction::Ptr 
        {aka boost::shared_ptr<Dyninst::InstructionAPI::Instruction>} and Dyninst::InstructionAPI::Instruction)
         while((insn = dec.decode())) {
                                  ^
         In file included from ....../boost/1.72.0/ppc64le/include/boost/shared_ptr.hpp:17,
                 from ... .../dyninst-10.1.0/build/include/dyn_regs.h:36,
                 from ... .../dyninst-10.1.0/build/include/dyntypes.h:183,
                 from ... .../dyninst-10.1.0/build/include/util.h:223,
                 from ... .../dyninst-10.1.0/build/include/InstructionAST.h:41,
                 from ... .../dyninst-10.1.0/build/include/Expression.h:35,
                 from ... .../dyninst-10.1.0/build/include/Instruction.h:38,
                 from ... .../dyninst-10.1.0/build/include/BPatch_point.h:57,
                 from commonSnippets.C:48:
    ... .../include/boost/smart_ptr/shared_ptr.hpp:547:18: note: candidate: boost::shared_ptr<T>& 
     boost::shared_ptr<T>::operator=(const boost::shared_ptr<T>&) [with T = Dyninst::InstructionAPI::Instruction]
     shared_ptr & operator=( shared_ptr const & r ) BOOST_SP_NOEXCEPT

Any advice to fix this? Thank you very much!

Shelton Ma

**Comment by emercadal** [comment]
Dear Shelton Ma,

Dyninst support in Extrae is outdated and v.10.x not still supported. We suggest you to disable it in the configure line of Extrae, adding `--without-dyninst`, and also its dependencies `--without-dwarf --without-elf`.

Happy new year!

**Comment by sheltongeosx** [comment]
Thank you Lau! That works. I disabled dyninst and the build is successful.

Happy new year!
