### ISSUE TITLE
Trace Merging Fails

### ISSUE THREAD

**Issue by davis-matthew** [bsc-performance-tools/extrae#55]
Hello,

When I try running extrae, the merging of the trace files fails.

```Extrae: Executing the merge process (using /src/TRACE.mpits).
merger: Extrae 3.8.3
mpi2prv: Assigned nodes < 0e93bef4c796 >
mpi2prv: Assigned size per processor < 0 bytes >
mpi2prv: File /src/set-0/TRACE@0e93bef4c796.0000014583000000000000.mpit is object 1.1.1 on node 0e93bef4c796 assigned to processor 0
mpi2prv: File /src/set-0/TRACE@0e93bef4c796.0000014583000000000001.mpit is object 1.1.2 on node 0e93bef4c796 assigned to processor 0
etc...
mpi2prv: Time synchronization has been turned off
mpi2prv: Checking for target directory existence... exists, ok!
fopen: No such file or directory
mpi2prv Error: Opening trace file /src/set-0/TRACE@0e93bef4c796.0000014583000000000000.mpit
AddFile_FS: No such file or directory
mpi2prv: Error creating file set
mpi2prv: Error! Some of the processors failed create trace descriptors
mpi2prv: An error has been encountered when generating the tracefile. Dying...
```

Running mpi2prv manually fails on opening the files as well. The files do exist and are in the location printed, but it seems that mpi2prv is unable to find them. Assistance on this would be very appreciated.

**Comment by emercadal** [comment]
Hello,

Did the application and instrumentation run correctly and without errors? What kind of application are you running? From the output you share it looks like a binary creating 2 pthreads, is this correct?

Could you please share with us how you used Extrae to instrument the application (which Extrae library you used, how did you load it, and the `xml` configuration file); as well as the contents of an `ls` on the `set-0` folder, as well as of the `TRACE.mpits` file? If it's possible, could you also share the `configure` parameters you used to install Extrae?

Regards,
