### ISSUE TITLE
configure: error: Cannot find MPI libraries file in the MPI specified path

### ISSUE THREAD

**Issue by Suiiiii** [bsc-performance-tools/extrae#83]
Hi,there, I am using intel oneapi and I want to install extrae with intel mpi.
./configure --with-mpi=/opt/intel/oneapi/mpi/2021.9.0

I have already put the correct PATH, but the ./configure can not find the MPI libraries files in the MPI specified path.
How to fix this problem?

many thanks

**Comment by Suiiiii** [comment]
Thanks to Mr. Johann Duffek at HSU solve the problem.
Extrae and Paraver are both working.
I am not a good git hub user, but he created a patch.

`
diff --git a/config/mpi-macros.m4 b/config/mpi-macros.m4
index 752385db..0b2e3de6 100644
--- a/config/mpi-macros.m4
+++ b/config/mpi-macros.m4
@@ -56,6 +56,10 @@ AC_DEFUN([AX_PROG_MPI],
          if test -f "${MPI_LIBSDIR}/libmpi/libmpi_ibm.so" ; then
             MPI_LIBSDIR=${MPI_LIBSDIR}/libmpi
          fi
+      elif test -d "${MPI_LIBSDIR}/release" ; then
+         if test -f "${MPI_LIBSDIR}/release/libmpi.so" ; then
+            MPI_LIBSDIR=${MPI_LIBSDIR}/release
+         fi
       fi
 
       dnl Check for the MPI header files.
`

**Comment by emercadal** [comment]
To deal with non standard paths for MPI libraries, Extrae's configure has the `--with-mpi-libs` option that receives the full path to the MPI libraries. This patch should not be needed if using this option.

Did you find any reason not to use this option that justifies the need for this patch.

**Comment by Suiiiii** [comment]
I tried with the --with-mpi-libs option. it does not work. 

FIRST
` ./configure --with-mpi-libs=/opt/intel/oneapi/mpi/latest/lib/release`

`configure: error: Attention! You have not passed the location of the MPI library through --with-mpi option. Please, use --with-mpi to specify the location of the MPI installation on your system, or if you don't want that Extrae supports MPI instrumentation use --without-mpi instead.
`
THEN

`./configure --with-mpi-libs=/opt/intel/oneapi/mpi/latest/lib/release --with-mpi=/opt/intel/oneapi/mpi/latest/lib/release `

`checking for MPI C compiler... configure: error: Cannot find ${MPI_HOME}/bin/mpicc. You can pass an alternate through MPICC environment variable.`


THEN

`./configure --with-mpi-libs=/opt/intel/oneapi/mpi/latest/lib/release --with-mpi=/opt/intel/oneapi/mpi/latest/lib/release MPICC=/opt/intel/oneapi/mpi/latest/bin/mpicc
`
```
configure: WARNING: Attention! It seems that your processor frequency changes on the fly through 'upowerd'. We add --enable-posix-clock to your configure line so as to use clock routines that can adapt to the processor frequency changes. However, if you know for sure that your processor speed does not change, you can proceed by adding --disable-posix-clock to use the fastest clock routines
checking for _POSIX_C_SOURCE to be at least 199309L... yes
checking for _POSIX_MONOTONIC_CLOCK to be defined... yes
checking for clock_gettime and CLOCK_MONOTONIC in default libraries... found
checking for peruse.h... ./configure: line 28551: test: not: binary operator expected
not available
checking for Fortran PMPI symbols name decoration scheme... 0 underscores
checking size of MPI_Status... 0
checking size of int... 0
./configure: line 28919: 0/0: division by 0 (error token is "0")
```

HOWEVER, if I apply this patch,I can just run like 

`./configure --prefix=/tmp/extrae --with-mpi=$I_MPI_ROOT --enable-openmp --with-papi=/usr --with-unwind=/usr --without-dyninst`

```

Package configuration for Extrae 4.0.4
-----------------------
Installation prefix: /tmp/extrae
Cross compilation: no
CC: gcc
CXX: g++
Binary type: 64 bits

MPI instrumentation: yes
	MPI home: /opt/intel/oneapi/mpi/2021.9.0
	MPI launcher: /opt/intel/oneapi/mpi/2021.9.0/bin/mpirun
	Fortran decoration: 0 underscores
	mixed C/Fortran libraries? yes
	shared libraries? yes
	MPI capabilities: 1-sided I/O MPI_Comm_spawn MPI3
GASPI instrumentation: no
OpenMP instrumentation: yes, through LD_PRELOAD
	GNU OpenMP: yes
	IBM OpenMP: no
	Intel OpenMP: yes
	OMPT: yes
OpenSHMEM instrumentation: no
pThread instrumentation: yes
	Support for pthread_barrier_wait: yes
	Support for pthread_cond_* calls: yes
CUDA instrumentation: no
OpenCL instrumentation: no
OPENACC instrumentation: no
Java instrumentation: unsupported

Performance counters: yes
	Performance API: PAPI
	PAPI home: /usr
	Sampling support: yes

PEBS sampling: yes

libbfd available: yes (/usr/lib/x86_64-linux-gnu)
libiberty available: yes (/usr/lib/x86_64-linux-gnu)
zlib available: yes (/usr/local)
libxml2 available: yes (/home/maosui/anaconda3)
BOOST available: no
callstack access: through libunwind (/usr)

Dynamic instrumentation: yes (not found)

Optional features:
------------------
On-line analysis: no
Clock routine: POSIX / clock_gettime, but don't need to link against posix clock library explicitly
Heterogeneous support: no
Parallel merge: yes
```

**Comment by emercadal** [comment]
Have you tried : 

`./configure --with-mpi=/opt/intel/oneapi/mpi/latest --with-mpi-libs=/opt/intel/oneapi/mpi/latest/lib/release`

The `--with-mpi-libs` option is used to specify only the path to MPI libraries, you still need to use `--with-mpi` for configure to find the includes and the binaries.

**Comment by Suiiiii** [comment]
It is like this now, saying that I dont have unwind. 
<img width="1388" alt="image" src="https://github.com/bsc-performance-tools/extrae/assets/40854317/8e0424fe-5b5a-40c7-b161-1b1240bbf6ec">


if I included the unwind path 
Then I get error like this

<img width="1393" alt="image" src="https://github.com/bsc-performance-tools/extrae/assets/40854317/f1d727a3-311e-48f7-8bbd-e7f8d93f41eb">

**Comment by Suiiiii** [comment]
If I use the patch, then the code is working with the unwind path. 

I am using intel oneAPI Toolkits, Base and HPC installed together
Intel® oneAPI Toolkits
Release 2023.1

**Comment by emercadal** [comment]
Strange, it seems that with `--with-mpi` and `--with-mpi-libs` configure finds the MPI instalation but complains about not finding `libunwind` but when specifying the location of libunwind then it stops finding the MPI libraries.

We don't understand how specifying the path for unwind affects finding the MPI libraries, and it doesn't seem to happen locally on our machines. I'm leaving the issue open until further updates.

Could you please share the full output of running?

`./configure --prefix=/tmp/extrae --with-mpi=$I_MPI_ROOT --with-mpi-libs=${I_MPI_ROOT}/lib/release --enable-openmp --with-papi=/usr --with-unwind=/usr --without-dyninst`

**Comment by Suiiiii** [comment]
with the commond you gave, now everything works fine now.
Then maybe this can be an example in your document.

[log.log](https://github.com/bsc-performance-tools/extrae/files/11934972/log.log)
