### ISSUE TITLE
Issues building extrae 4.0.4 with Intel OneAPI compiler

### ISSUE THREAD

**Issue by cniethammer** [bsc-performance-tools/extrae#84]
The extrae 4.0.4 release cannot be built with the newer Intel OneAPI compilers due to problems with configure from the current release tarball available on https://tools.bsc.es/downloads .
The issue can be resolved by using autoconf 2.70 or newer to generate the packaged configure script.
Details e.g. https://github.com/HDFGroup/hdf5/issues/2563

It would be good if you can update your release pipeline for the tarballs accordingly.

**Comment by gllort** [comment]
Updated, thank you!
