### ISSUE TITLE
facing issue with compilation of extrae-4.0.4

### ISSUE THREAD

**Issue by ranjit02** [bsc-performance-tools/extrae#86]
I am compiling the extrae-4.0.4 on an XC-40 machine with the cray-gnu environment with all supported libraries but it's giving me the same error of binutils please find the configure command and error message below:

./configure --with-binutils=/home/sranjit/profile/binutils/x86_64/  --with-mpi=/usr/lib64/mpi/gcc/mvapich2  --with-xml-prefix=/usr/lib64   --disable-xmltest  --enable-sampling --prefix=/home/sranjit/profile/exe/extrae_v4.0.4   --with-papi=/opt/cray/pe/papi/5.5.1.1 --with-unwind=/home/sranjit/profile/deps/unwind_1.16.1 --without-dyninst CC=cc CFLAGS='-O3 -g' LDFLAGS='-O3 -g' CXX=CC CXXFLAGS='-O3 -g' F77=ftn FFLAGS='-O3 -g'

![image](https://github.com/bsc-performance-tools/extrae/assets/59292502/a399456a-d4bd-4347-bc91-dab146be7d28)
 even though binutils is installed and the path is given still it's giving the above issue same happening with PAPI that also installed at the given path but it's not taking the same.

Any help will be appreciated.

**Comment by gllort** [comment]
Can you please post the file 'config.log'?

**Comment by ranjit02** [comment]
Resolved
